### ISSUE TITLE
Feature request - Support PF2E (System agnostic possible?)

### ISSUE THREAD

**Issue by roi007leaf** [roth-michael/region-attacher#5]
As title says, it would be great if this module could support pf2e templates as well

**Comment by roi007leaf** [comment]
Also, instead of having it depend on a checkbox on the item, maybe have a dialog on evet template creation asking if a region should be attached?

**Comment by roi007leaf** [comment]
I could not find a way to attack a region to an existing template, can you share a recording of this? using pf2e system of course

**Comment by roth-michael** [comment]
I actually think it's a bug I introduced in a previous update that would even break the behavior in dnd5e. Working on a fix. At least today I should be able to have that fix out. The pf2e item sheet integration may take longer.

**Comment by roi007leaf** [comment]
@roth-michael 
` if (parentDocument instanceof TileDocument || parentDocument instanceof MeasuredTemplateDocument) {`
def need to add support for MeasuredTemplateDocumentPF2e :-D

**Comment by roth-michael** [comment]
`MeasuredTemplateDocumentPF2e` inherits `MeasuredTemplateDocument` 😉 so should be good on that front. I actually also now have the sheet override working:
![image](https://github.com/user-attachments/assets/319d50a6-db74-4d6e-a5b7-1fefae5d2436)

Now just need to actually change the logic so that the configured region does indeed get attached to the template.

**Comment by roi007leaf** [comment]
Cool!, make sure the region itself also works lol :D

**Comment by roth-michael** [comment]
Yeah, I've got it working on my side now. Question for you, since I'm unfamiliar with pf2e as a system: Which types of item sheets should I make sure the option shows up for? E.g. at first glance of course spell sheets, but are there any other types of items that can create templates that should also be able to have regions linked?

**Comment by roi007leaf** [comment]
Mostly spells, I say leave it for future feature requests if something pops up @roth-michael

**Comment by roth-michael** [comment]
Sounds good. Should have an update out later today (wanna fix it up for the new dnd5e system release, otherwise I'd release immediately).

**Comment by roth-michael** [comment]
Alright, won't be getting to the dnd5e update today, so just released 1.5.0 with PF2e functionality. Lemme know if it works as expected and I'll close the issue if so.

**Comment by roi007leaf** [comment]
doesnt work, region config window doesnt open @roth-michael

**Comment by roth-michael** [comment]
You first have to make it one that would prompt for a template. e.g. its area selection must be non-empty.

**Comment by roth-michael** [comment]
1.5.1 out now that should fix the other issue (for new templates, at least).

**Comment by roi007leaf** [comment]
Checking now

**Comment by roi007leaf** [comment]
Works as expected!
